### ISSUE TITLE
[Bug]: Incorrect usage of `vault.process`

### ISSUE THREAD

**Issue by liamcain** [chrisgrieser/obsidian-quadro#6]
### Bug Description

Weird, my inline comment got lost. Github seems to know it exists because it says there are 6 comments on the commit, but its not showing for some reason.

Here's roughly what I write:

`vault.process` is intended to handle the read and write from disk. To properly perform atomic modifications using vault.process, you need to use the fileContents string that's provided to the `process` callback function.

You need to get rid of the `read()` call and instead move all the file modifications into the process callback function.

```ts
// Current
let fileContents = vault.read(file);
let modifiedContents = transformFileContents(fileContents);
vault.process(file, (_unusedFileContents: string) => {
  // latest file contents are ignored.
  return modifiedContents;
});

// Fixed
vault.process(file, fileContents => {
  let modifiedContents = transformFileContents(fileContents);
  return modifiedContents;
});
```

Not only does this ensure the latest file contents are used, but it avoids reading the file contents twice, so it will be more efficient.

**Comment by chrisgrieser** [comment]
Regarding this, one thing that I was asking myself was whether vault.process is unconditionally preferred, or only preferred if all things being equal?

In 3 cases I have not "properly" implemented vault.process since there were some downsides to it:
1. it would in a particular case decrease readability imo
2. the text transformation being in a function prevents me from aborting the outer file modification function without since convoluted code rewriting (throwing an error, wrapping in try-catch, etc)

If vault.process is only somewhat preferred and not *always*, I'd keep using vault.modify in such cases, since in this 3 cases is non-large, single files being changed where a small performance benefit would not be worth the decreased readability to me personally.

**Comment by liamcain** [comment]
While there are some exceptions to the rule, reviewing your code, none of your usages qualify as exceptions. There's no performance benefit to using `process` vs `read+modify`. Under the hood, process is doing the same thing, but it also adds additional checks to protect against data loss. Imagine that the file was modified, and now the file is getting saved to disk the same time that you're code is executing. When you call `modify` you risk saving old contents to disk which would save over the latest changes.

**Comment by chrisgrieser** [comment]
I see, got it. 

If vault.process is basically always preferred, shouldn't vault.modify be deprecated then?

**Comment by liamcain** [comment]
I don't think so; there's nothing inherently wrong with `vault.modify`. It's just a naive function that writes text to disk. The issue is with the pattern in general. We can improve the documentation to make it more clear when you should be using `process` though.

**Comment by chrisgrieser** [comment]
> We can improve the documentation to make it more clear when you should be using`process` though.

I think some clarifications when to use `vault.modify` would also be relevant, since after your elaborations, it is not clear to me what the use case of that API is.

---

anyway, I fixed the problematic usages of `vault.process` in https://github.com/chrisgrieser/obsidian-quadro/commit/b6a82b107d4075d7cb9d0b327f9c3c034d9c4e9d
